services:
  - type: web
    name: your-bot-service # Название вашего сервиса на Render
    env: python
    pythonVersion: 3.11.9 # <-- ДОБАВЬТЕ ЭТУ СТРОКУ (или 3.10.12, или 3.9.18)
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    # ... остальные настройки, если они есть ...
